apiVersion: v1
kind: Secret
metadata:
  name: payment-system-secrets
  namespace: payment-system
type: Opaque
stringData:
  # JWT configuration
  JWT_SECRET: "replace-with-secure-random-jwt-secret-in-production"
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRATION_MINUTES: "60"
  
  # Node configuration
  NODE_ID: "node1"
  CLUSTER_NODES: "node1,node2,node3" 